name: Build main
on:
  push:
    branches: main
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'

  pull_request:
  workflow_dispatch:

jobs:
  ci-test:
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

    - name: Build Kernel
      uses: ./
      with:
          kernel-url: https://github.com/vados-dev/android_kernel_sprd_lucyzh
          kernel-dir: sprd
          kernel-branch: main
          config: sl8541e_defconfig
          arch: arm
          aosp-gcc: false
          aosp-clang: false
          ksu: false
          ksu-version: main
          android-version: 
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: false
